# Generated by Django 3.2 on 2022-12-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование курса')),
                ('date_started', models.DateField(verbose_name='Дата начала курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Язык программирования')),
                ('month_to_learn', models.IntegerField(verbose_name='Продолжительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('work_study_place', models.CharField(max_length=50, null=True, verbose_name='Место учебы/работы')),
                ('has_own_notebook', models.BooleanField()),
                ('preferred_os', models.CharField(choices=[], max_length=50, verbose_name='Предпочитаемая ОС')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('main_work', models.CharField(max_length=50, null=True, verbose_name='Основное место работы')),
                ('experience', models.DateField(verbose_name='Дата начала работы')),
                ('students', models.ManyToManyField(related_name='mentors', through='user.Course', to='user.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mentor'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
